repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      additional_dependencies: [ruff==0.4.4]
    - id: ruff-format
